name: Weekly System Maintenance

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  system-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run system checks
        run: ./scripts/check-status.sh
      
      - name: Commit updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/exports/
          git diff --quiet && git diff --staged --quiet || git commit -m "Weekly system maintenance update"
          git push
